### ISSUE TITLE
gitsubmodule pointing nowhere

### ISSUE THREAD

**Issue by umlaeute** [extendedview/extended_view_toolkit#2]
the git-submodule for `ev-glsl/glsl/v001` points to

```
https://github.com/extendedview/v001.git
```

but unfortunately this repository does not exist.

**Comment by m---w** [comment]
Thanks. The submodule is now removed.
The shader library will be included in the next release.

**Comment by umlaeute** [comment]
thanks. i notived however that a file from the `v001` folder is referenced in `ev-glsl/ev_glsl_mix2_dsp.pd`.

should i simply ignore this?

**Comment by m---w** [comment]
This reference to the fragment shader gets overwritten at creation and can be ignored. However, I now changed it to initialize with something neutral.

**Comment by umlaeute** [comment]
thanks for clarification.
